### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by WaterFenix** [cheloveg/randArbat#1]
Hello, dear Cheloveg.

I found a bug in the output animation, please fix it.

Good luck in your development!

![изображение](https://user-images.githubusercontent.com/59115392/71308045-2d812c80-2408-11ea-855f-2a2e2dafff69.png)

**Comment by cheloveg** [comment]
Thanks for report! I fix it in next comment!

**Comment by WaterFenix** [comment]
OK, good luck!

**Comment by cheloveg** [comment]
Fixed!
